services:
  - type: web
    name: voice-interview-assistant
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
        
